spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001


mybatis-plus:
  type-aliases-package: squirrel.pojo                         #所有实体类别名类所在包
  mapper-locations: classpath:mapper/**/*.xml                 #mapper映射文件


spring:
  profiles: 8001
  application:
    name: book
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://localhost:3306/zroom1        #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                            #数据可连接的最小维持连接数
      initial-size: 5                        #初始化连接数
      max-total: 5                           #最大连接数
      max-wait-millis: 200                   #等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/,http://eureka7005.com:7005/eureka/,http://eureka7006.com:7006/eureka/
  instance:
    instance-id: provider-book-zroom1-8001
    prefer-ip-address: true     #访问路径可以显示IP地址

---
server:
  port: 8002


mybatis-plus:
  type-aliases-package: squirrel.pojo                         #所有实体类别名类所在包
  mapper-locations: classpath:mapper/**/*.xml                 #mapper映射文件


spring:
  profiles: 8002
  application:
    name: book
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://localhost:3306/zroom2        #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                            #数据可连接的最小维持连接数
      initial-size: 5                        #初始化连接数
      max-total: 5                           #最大连接数
      max-wait-millis: 200                   #等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/,http://eureka7005.com:7005/eureka/,http://eureka7006.com:7006/eureka/
  instance:
    instance-id: provider-book-zroom2-8002
    prefer-ip-address: true     #访问路径可以显示IP地址

---
server:
  port: 8003


mybatis-plus:
  type-aliases-package: squirrel.pojo                         #所有实体类别名类所在包
  mapper-locations: classpath:mapper/**/*.xml                 #mapper映射文件


spring:
  profiles: 8003
  application:
    name: game
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://localhost:3306/zroom1        #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                            #数据可连接的最小维持连接数
      initial-size: 5                        #初始化连接数
      max-total: 5                           #最大连接数
      max-wait-millis: 200                   #等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/,http://eureka7005.com:7005/eureka/,http://eureka7006.com:7006/eureka/
  instance:
    instance-id: provider-game-zroom1-8003
    prefer-ip-address: true     #访问路径可以显示IP地址

---
server:
  port: 8004


mybatis-plus:
  type-aliases-package: squirrel.pojo                         #所有实体类别名类所在包
  mapper-locations: classpath:mapper/**/*.xml                 #mapper映射文件


spring:
  profiles: 8004
  application:
    name: game
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://localhost:3306/zroom2        #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                            #数据可连接的最小维持连接数
      initial-size: 5                        #初始化连接数
      max-total: 5                           #最大连接数
      max-wait-millis: 200                   #等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/,http://eureka7005.com:7005/eureka/,http://eureka7006.com:7006/eureka/
  instance:
    instance-id: provider-game-zroom2-8004
    prefer-ip-address: true     #访问路径可以显示IP地址

---
server:
  port: 8005


mybatis-plus:
  type-aliases-package: squirrel.pojo                         #所有实体类别名类所在包
  mapper-locations: classpath:mapper/**/*.xml                 #mapper映射文件


spring:
  profiles: 8005
  application:
    name: play
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://localhost:3306/zroom1        #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                            #数据可连接的最小维持连接数
      initial-size: 5                        #初始化连接数
      max-total: 5                           #最大连接数
      max-wait-millis: 200                   #等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/,http://eureka7005.com:7005/eureka/,http://eureka7006.com:7006/eureka/
  instance:
    instance-id: provider-play-zroom1-8005
    prefer-ip-address: true     #访问路径可以显示IP地址

---
server:
  port: 8006


mybatis-plus:
  type-aliases-package: squirrel.pojo                         #所有实体类别名类所在包
  mapper-locations: classpath:mapper/**/*.xml                 #mapper映射文件


spring:
  profiles: 8006
  application:
    name: play
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://localhost:3306/zroom2        #数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                            #数据可连接的最小维持连接数
      initial-size: 5                        #初始化连接数
      max-total: 5                           #最大连接数
      max-wait-millis: 200                   #等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/,http://eureka7004.com:7004/eureka/,http://eureka7005.com:7005/eureka/,http://eureka7006.com:7006/eureka/
  instance:
    instance-id: provider-play-zroom2-8006
    prefer-ip-address: true     #访问路径可以显示IP地址
